/**
 * RSA and EC key pairs, generated by the browser's own Web Crypto.
 *
 * The reason this tool is worth having is what it does *not* do. A site that
 * generates a key pair on its server has, by construction, held your private
 * key — you have to take its word that it was not logged, cached or kept. Here
 * the pair is produced by `crypto.subtle` inside the tab and never leaves it,
 * so there is nothing to take anyone's word about.
 *
 * Only RSA and EC are offered. Ed25519 is the better modern default, but
 * browser support for it in Web Crypto is still uneven, and an algorithm in
 * the list that fails on some browsers is worse than one that is absent.
 */

export type KeyAlgorithm = 'rsa-2048' | 'rsa-3072' | 'rsa-4096' | 'ec-p256' | 'ec-p384' | 'ec-p521';

export interface KeyChoice {
  id: KeyAlgorithm;
  label: string;
  /** Shown under the picker, so the choice is not just a number. */
  hint: string;
}

export const KEY_CHOICES: readonly KeyChoice[] = [
  {
    id: 'ec-p256',
    label: 'EC P-256',
    hint: 'Fast, small, and the usual default. Comparable to RSA 3072.',
  },
  { id: 'ec-p384', label: 'EC P-384', hint: 'A larger curve, where a policy asks for one.' },
  { id: 'ec-p521', label: 'EC P-521', hint: 'Largest of the common curves. Rarely required.' },
  {
    id: 'rsa-2048',
    label: 'RSA 2048',
    hint: 'The long-standing minimum. Still widely required for compatibility.',
  },
  {
    id: 'rsa-3072',
    label: 'RSA 3072',
    hint: 'What guidance now recommends where RSA is mandated.',
  },
  {
    id: 'rsa-4096',
    label: 'RSA 4096',
    hint: 'Slow to generate, and rarely buys anything over 3072.',
  },
];

export interface KeyPairPem {
  privatePem: string;
  publicPem: string;
}

/** Web Crypto parameters for each offered choice. */
function paramsFor(algorithm: KeyAlgorithm): RsaHashedKeyGenParams | EcKeyGenParams {
  switch (algorithm) {
    case 'rsa-2048':
    case 'rsa-3072':
    case 'rsa-4096':
      return {
        name: 'RSASSA-PKCS1-v1_5',
        modulusLength: Number(algorithm.slice(4)),
        // 65537, the standard public exponent.
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
        hash: 'SHA-256',
      };
    case 'ec-p256':
      return { name: 'ECDSA', namedCurve: 'P-256' };
    case 'ec-p384':
      return { name: 'ECDSA', namedCurve: 'P-384' };
    case 'ec-p521':
      return { name: 'ECDSA', namedCurve: 'P-521' };
  }
}

/**
 * Generates a pair and returns both halves as PEM.
 *
 * PKCS#8 for the private half and SPKI for the public one, which are the
 * formats OpenSSL, ssh-keygen consumers and Web Crypto itself all read back —
 * and the same PKCS#8 the JWT Editor here accepts.
 */
export async function generateKeyPair(algorithm: KeyAlgorithm): Promise<KeyPairPem> {
  const pair = await crypto.subtle.generateKey(paramsFor(algorithm), true, ['sign', 'verify']);
  const [privateDer, publicDer] = await Promise.all([
    crypto.subtle.exportKey('pkcs8', pair.privateKey),
    crypto.subtle.exportKey('spki', pair.publicKey),
  ]);
  return {
    privatePem: toPem(new Uint8Array(privateDer), 'PRIVATE KEY'),
    publicPem: toPem(new Uint8Array(publicDer), 'PUBLIC KEY'),
  };
}

/** DER bytes to a PEM block, wrapped at 64 characters as the format expects. */
export function toPem(der: Uint8Array, label: string): string {
  let binary = '';
  for (const byte of der) {
    binary += String.fromCharCode(byte);
  }
  const body = btoa(binary)
    .replace(/(.{64})/g, '$1\n')
    .trimEnd();
  return `-----BEGIN ${label}-----\n${body}\n-----END ${label}-----`;
}
