import { Tool, ToolCategory } from './tool.model';

export const TOOL_CATEGORIES: ToolCategory[] = ['Developer', 'Converter', 'Document'];

/**
 * The catalog of free utilities. Keep this list as the single source of truth —
 * the homepage grid, search and category filter are all derived from it, and the
 * shared backend exposes the same catalog at GET /api/tools.
 */
export const TOOLS: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate and minify JSON, convert to/from YAML and query with JSONPath.',
    icon: 'data_object',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'json-to-types',
    name: 'JSON to Types',
    description: 'Turn JSON into TypeScript, Python, Rust, Kotlin, Java, JSON Schema and more.',
    icon: 'code',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT headers and claims, and verify the signature.',
    icon: 'key',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Compute MD5, CRC32, SHA and keyed HMAC digests of text or a file.',
    icon: 'tag',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two blocks of text line by line, in a split or unified view.',
    icon: 'difference',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test a regular expression live, with match highlighting and capture groups.',
    icon: 'find_replace',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'cron-explainer',
    name: 'Cron Explainer',
    description: 'Read a cron expression in plain English and preview its next run times.',
    icon: 'alarm',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Turn text, a URL or Wi-Fi details into a QR code and download it as PNG or SVG.',
    icon: 'qr_code_2',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, PascalCase and a slug.',
    icon: 'text_fields',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL for a dozen dialects, right in your browser.',
    icon: 'storage',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'code-formatter',
    name: 'Code Formatter',
    description: 'Beautify HTML, CSS, JS, TypeScript, JSON, Markdown, YAML, GraphQL and XML.',
    icon: 'integration_instructions',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random v4 or time-ordered v7 UUIDs in bulk.',
    icon: 'fingerprint',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'color-converter',
    name: 'Color Converter',
    description: 'Convert HEX, RGB, HSL, OKLCH and LAB, generate palettes and check WCAG contrast.',
    icon: 'palette',
    category: 'Developer',
    ready: true,
  },
  {
    slug: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode text or files to and from Base64.',
    icon: 'swap_horiz',
    category: 'Converter',
    ready: true,
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Shrink PNG and JPEG images to JPEG or WebP, right in your browser.',
    icon: 'compress',
    category: 'Converter',
    ready: true,
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates.',
    icon: 'schedule',
    category: 'Converter',
    ready: true,
  },
  {
    slug: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write Markdown with a live, side-by-side preview.',
    icon: 'edit_note',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-convert',
    name: 'PDF Convert',
    description: 'Turn a PDF into an editable Word or rich-text file.',
    icon: 'sync_alt',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Make a scanned PDF searchable and selectable with text recognition.',
    icon: 'document_scanner',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-compress',
    name: 'PDF Compress',
    description: 'Shrink a PDF by downsampling the images inside it, with real size savings.',
    icon: 'compress',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-viewer',
    name: 'PDF Viewer',
    description: 'Open and read a PDF with thumbnails, search and zoom — no upload.',
    icon: 'picture_as_pdf',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine several PDF files into a single document.',
    icon: 'picture_as_pdf',
    category: 'Document',
    ready: true,
  },
  {
    slug: 'pdf-split',
    name: 'PDF Split',
    description: 'Extract selected pages from a PDF, or split it into one file per page.',
    icon: 'content_cut',
    category: 'Document',
    ready: true,
  },
];
